### ISSUE TITLE
Code does not compile as no CMakeLists.txt is provided

### ISSUE THREAD

**Issue by bolding** [BoldingBruggeman/flexout#1]
@bolding making some small issue testing

**Comment by jornbr** [comment]
it's only a pre-alpha version :-) Try now

**Comment by bolding** [comment]
but did you read the comment?

**Comment by jornbr** [comment]
yes (I use the "view it on GitHub" option)

**Comment by bolding** [comment]
Where do you set that? 
Did you see my Milestones as well :-)

**Comment by jornbr** [comment]
at the bottom of the mail
I can see the open milestones - Is that my to-do list you're adding to? ;-)

**Comment by bolding** [comment]
The source directory

    /home/kb/source/repos/FLEXOUT/flexout/lib/fortran-yaml

  does not contain a CMakeLists.txt file.

Did you not commit everything? I don't see any additional flags to specify yaml folder.

**Comment by jornbr** [comment]
it's a submodule - try

git submodule update --init

**Comment by bolding** [comment]
I actually think ths could develop to be quite advantagous - Nicolas's bug report would have fitted perfectly in this system - and your answer as well. No one will ever read the email again.

Should have thought about that.

**Comment by bolding** [comment]
CMake Error at CMakeLists.txt:59 (target_link_libraries):
  Target "yaml" of type OBJECT_LIBRARY may not be linked into another target.
  One may link only to STATIC or SHARED libraries, or to executables with the
  ENABLE_EXPORTS property set.

**Comment by jornbr** [comment]
Outdated cmake I think - though it could be an idea to implement workarounds for older cmake versions

**Comment by bolding** [comment]
kb@orca ~/source/repos/FLEXOUT/flexout/src $ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by bolding** [comment]
if             ${YAML_SOURCES}
is populated do you need the target_link_library?

**Comment by jornbr** [comment]
you need 3.12 - but I'll change the YAML lib to become s static library rather than an object library, which should fix this for older cmakes. ${YAML_SOURCES} is redundant and will be removed (and is currently empty

**Comment by jornbr** [comment]
now done

**Comment by bolding** [comment]
and works
